- hosts: localhost
  connection: local
  tasks:
    - name: Open the web page with firefox
      become: false
      shell: lxc list | grep lb1 | awk '{print "http://"$6}' | xargs  firefox  & 
      tags: open_webpage

    - name: Open the web page with firefox
      become: false
      shell: lxc list | grep lb1 | awk '{print "http://"$6":32700"   }' | xargs  firefox   
      tags: open_stats
